sudo: required
language: cpp

env:
  global:
    - IsTravis=1
    - MAKEFLAGS="-j 2"

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get -qq install libgsl0-dev;
    elif [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install gsl;
    fi

script:
  - make

