sudo: required
language: cpp

env:
  global:
    - IsTravis=1

services:
  - docker

install:
  - docker pull ubuntu:16.04

compiler:
  - g++
  - clang++

addons:
  apt:
    packages:
    - libgsl-dev

script:
  - make test

after_success:
  - sudo pip install cpp-coveralls
  - coveralls -b .
