sudo: required
language: cpp

env:
  global:
    - IsTravis=1

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get -qq update
      sudo apt-get -qqy install libgsl0-dev
    elif [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update
      brew install libgsl
    fi

script:
  - make test

after_success:
  - sudo pip install cpp-coveralls
  - coveralls -b .
