sudo: required
language: cpp

env:
  global:
    - IsTravis=1

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

addons:
  apt:
    packages:
    - libgsl0-dev

script:
  - make test

after_success:
  - sudo pip install cpp-coveralls
  - coveralls -b .
