language: cpp

env:
  global:
    - IsTravis=1

os:
  - linux
  - osx

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.8 -y

compiler:
  - g++-4.8
  - clang++

addons:
  apt:
    packages:
    - libgsl-dev

script:
  - make
  - make test

after_success:
  - sudo pip install cpp-coveralls
  - coveralls -b .
